---
title: "Modirisk_patch_GRiSCiColl"
author: "Dimitri Brosens"
date: "2023-06-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:

```{r}
library(tidyverse)      # To do data science
library(tidylog)        # To provide feedback on dplyr functions
library(magrittr)       # To use %<>% pipes
library(here)           # To find files
library(janitor)        # To clean input data
library(readxl)         # To read Excel files
library(digest)         # To generate hashes
library(rgbif)          # To use GBIF services
```

# Read source data

Create a data frame `input_data` from the source data:

```{r}
input_data <- read_csv(here::here("datasets", "modirisk-occurrences", "Collections_data", "data", "processed", "occurrenceCulibel.csv"))
```

# Preprocessing

## Tidy data

Clean data somewhat:

```{r}
input_data %<>% remove_empty("rows")
```

# Darwin Core mapping

## Create occurrence core

Create a dataframe with occurrence data:

```{r}
occurrence <- input_data
```

# Remove obsolete columns (Bijvangst)

```{r}
occurrence %<>% select(-c(collectionCode))
```

Add columns:

```{r eval = FALSE}
occurrence %<>%
  mutate(institutionID = "https://ror.org/02y22ws83") %>%
  mutate(collectionCode = "INV-ENT")
```

Save to CSV:

```{r}
write_csv(occurrence, here::here("datasets", "modirisk-occurrences", "Collections_data", "data", "processed", "occurrence.csv"), na = "")

```

